FROM w251/tensorflow:dev-tx2-4.2_b158-py3

RUN apt update
# RUN apt-get install -y --fix-missing sudo
# RUN apt-get install -y --fix-missing \
RUN apt install -y \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgtk2.0-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    wget
# RUN apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN pip3 install jupyter
# RUN pip3 install keras
RUN pip3 install pandas
ENV DEBIAN_FRONTEND=noninteractive
RUN apt install -y python3-sklearn

RUN pip3 install keras
# RUN pip3 install scikit-learn
WORKDIR /
RUN mkdir -p notebooks
WORKDIR /notebooks
# RUN wget https://s3-eu-west-1.amazonaws.com/darraghdog1/train.csv.zip
# RUN wget https://github.com/MIDS-scaling-up/v2/blob/darragh_hw04/week04/hw/w251_homework04.ipynb
# RUN wget https://raw.githubusercontent.com/MIDS-scaling-up/v2/darragh_hw04/week04/hw/w251_homework04.ipynb
#RUN wget https://s3-eu-west-1.amazonaws.com/darraghdog1/w251_homework04.ipynb
EXPOSE 8888

# Jupyter
CMD jupyter notebook  --no-browser --ip=0.0.0.0 --allow-root

