FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf2.3-py3


# thanks Dusty
# https://github.com/dusty-nv/jetson-containers/blob/master/Dockerfile.ml
#
# JupyterLab
#
#

RUN apt update
RUN apt install -y libffi-dev
RUN apt install -y libzmq3-dev
RUN apt install -y python3-cffi
RUN apt install -y python3-zmq
# RUN apt install -y python3-tornado
# RUN apt install -y python3-argon2
RUN apt install -y python3-pandocfilters
RUN pip3 install jupyter jupyterlab --verbose
RUN apt install -y python3-matplotlib
RUN pip3 install tensorflow-hub
RUN pip3 install tensorflow-datasets
#RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager@2

# RUN jupyter lab --generate-config
# RUN python3 -c "from notebook.auth.security import set_password; set_password('nvidia', '/root/.jupyter/jupyter_notebook_config.json')" 

CMD /bin/bash -c "jupyter lab --ip 0.0.0.0 --port 8888 --allow-root"
