FROM w251/cuda:tx2-3.3_b39

# validated on 3/24/2019
# to run this:
# docker run --rm -v /tmp:/tmp -v /dev:/dev --ipc=host --net=host --privileged -e DISPLAY=$DISPLAY -ti drl sh -c "cd /jetson-reinforcement/build/aarch64/bin && ./gazebo-arm.sh"

RUN apt update
RUN apt install -y git cmake

WORKDIR /
RUN git clone http://github.com/dusty-nv/jetson-reinforcement
WORKDIR /jetson-reinforcement
RUN git submodule update --init
# RUN mkdir build
# WORKDIR /jetson-reinforcement/build

RUN sed -i -e 's/apt-get install -y/apt-get install/g' CMakePreBuild.sh && sed -i -e 's/apt-get install/apt-get install -y/g' CMakePreBuild.sh
RUN sed -i '32,39d' CMakePreBuild.sh && sed -i '32i sudo apt-get install -y gazebo7 libgazebo7-dev' CMakePreBuild.sh
RUN sed -i '68,75d' CMakePreBuild.sh && sed -i '68i sudo apt-get install -y ipython ipython-notebook; sudo pip install jupyter' CMakePreBuild.sh

# Build
RUN mkdir build
WORKDIR build
RUN cmake ../
RUN make -j6

# locale madness
RUN apt install -y locales locales-all gnome-terminal
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
