FROM w251/keras:dev-tx2-4.3_b132


# this dockerfile is for Jetson tx2 jetpack 4.3
# to build:
# docker build -t hw04 -f Dockerfile.dev-tx2-4.3_b132 .
# to run:
# docker run --rm --privileged -p 8888:8888 -d hw04
# This should start Jupyter on port 8888 and print the container id
# to get the security token, wait 5-10 seconds then do:
# docker log <container id from above>
# access by pointing your browser to http://ip_of_your_tx2:8888
# use the token from above

# this dockerfile is experimental
# it should work, but watch your memory utilization!
# if this dies -- make sure you enable swap (see hw01)
RUN  apt-get remove -y python && rm /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python && pip install --upgrade tensorflow-hub
WORKDIR /
RUN mkdir -p notebooks
COPY transfer_learning_with_hub.ipynb /notebooks/transfer_learning_with_hub.ipynb

WORKDIR notebooks
